### ISSUE TITLE
oauth2_provider migration failed due to duplicates labels on Django 1.7

### ISSUE THREAD

**Issue by H0neyBadger** [evonove/django-oauth-toolkit#210]
Hello,
I get the following issue when I try to migrate django-oauth-toolkit data model :
```
[user@server dir]# python manage.py makemigrations oauth2_provider
Migrations for 'oauth2_provider':
  0001_initial.py:
    - Create model AccessToken
    - Create model Application
    - Create model Grant
    - Create model RefreshToken
    - Add field application to accesstoken
    - Add field user to accesstoken
```

```
[user@server dir]# python manage.py migrate oauth2_provider
Operations to perform:
  Apply all migrations: oauth2_provider
Running migrations:
  Applying oauth2_provider.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/python3.4/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/python3.4/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/python3.4/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/python3.4/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/python3.4/site-packages/django/db/migrations/state.py", line 57, in render
    self.apps = Apps([AppConfigStub(label) for label in sorted(self.real_apps + list(app_labels))])
  File "/python3.4/site-packages/django/apps/registry.py", line 56, in __init__
    self.populate(installed_apps)
  File "/python3.4/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: oauth2_provider
```

Do you have a workaround for this issue?
It seems related to this doc 
https://docs.djangoproject.com/en/1.7/ref/applications/#for-application-authors

**Comment by LennyLip** [comment]
Got this issue too. 
I don't  know why, but i have 0002_adding_indexes.py from South in \migrations folder.
That was my problem. see migration folder, there are must be
\0001_initial.py
\__init__.py

only.

**Comment by IamPsi** [comment]
Update your version of Django and try. It worked for me.

**Comment by poswald** [comment]
There has been a small patch in the migrations since this was reported. Can you please retry and reopen this with more details if you still see issues.
