### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by gio82** [evonove/django-oauth-toolkit#266]
```
Internal Server Error: /o/token/
Traceback (most recent call last):
 File "/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
   return self.dispatch(request, *args, **kwargs)
 File "/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
   return bound_func(*args, **kwargs)
 File "/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
   return view_func(*args, **kwargs)
 File "/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/lib/python2.7/site-packages/braces/views/_forms.py", line 22, in dispatch
   return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
 File "/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
   return handler(request, *args, **kwargs)
 File "/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
   return bound_func(*args, **kwargs)
 File "/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
   return view(request, *args, **kwargs)
 File "/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/lib/python2.7/site-packages/oauth2_provider/views/base.py", line 170, in post
   url, headers, body, status = self.create_token_response(request)
 File "/lib/python2.7/site-packages/oauth2_provider/views/mixins.py", line 124, in create_token_response
   return core.create_token_response(request)
 File "/lib/python2.7/site-packages/oauth2_provider/oauth2_backends.py", line 106, in create_token_response
   headers)
 File "/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
   return f(endpoint, uri, *args, **kwargs)
 File "/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 100, in create_token_response
   request, self.default_token_type)
 File "/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 63, in create_token_response
   refresh_token=self.issue_new_refresh_tokens)
 File "/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/tokens.py", line 270, in create_token
   self.request_validator.save_bearer_token(token, request)
 File "/lib/python2.7/site-packages/oauth2_provider/oauth2_validators.py", line 291, in save_bearer_token
   assert()  # TODO though being here would be very strange, at least log the error
AssertionError
```

**Comment by masci** [comment]
Duplicated of #206
