### ISSUE TITLE
The oauthlib-1.0.0 breaks django-oauth-toolkit-0.8.2

### ISSUE THREAD

**Issue by abarto** [evonove/django-oauth-toolkit#277]
oauthlib-1.0.0 was released recently and it seems to break the current version of django-oauth-tookit. The site works just fine with oauthlib-0.7.2. Here's a traceback showing the issue:

Internal Server Error: /o/token/
Traceback (most recent call last):
  File "venv/lib64/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "venvlib64/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "venv/lib64/python3.4/site-packages/braces/views/_forms.py", line 22, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "venv/lib64/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "venv/lib64/python3.4/site-packages/oauth2_provider/views/base.py", line 170, in post
    url, headers, body, status = self.create_token_response(request)
  File "venv/lib64/python3.4/site-packages/oauth2_provider/views/mixins.py", line 124, in create_token_response
    return core.create_token_response(request)
  File "venv/lib64/python3.4/site-packages/oauth2_provider/oauth2_backends.py", line 106, in create_token_response
    headers)
  File "venv/lib64/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "venv/lib64/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 100, in create_token_response
    request, self.default_token_type)
  File "venv/lib64/python3.4/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 99, in create_token_response
    if self.request_validator.client_authentication_required(request):
  File "venv/lib64/python3.4/site-packages/oauth2_provider/oauth2_validators.py", line 146, in client_authentication_required
    if request.client_id and request.client_secret:
  File "venv/lib64/python3.4/site-packages/oauthlib/common.py", line 409, in __getattr__
    raise AttributeError(name)
AttributeError: client_secret

**Comment by abarto** [comment]
Pull request with a fix (I've tested it against a couple of my sites) https://github.com/evonove/django-oauth-toolkit/pull/278

**Comment by masci** [comment]
I've already in place a set of patches for oauthlib 1.0 compatibility. I haven't merged them yet because there was a bug on oauthlib, fixed on master. I'm afraid we have to wait a 1.0.1 release of oauthlib to fix.

**Comment by devoto13** [comment]
Version [1.0.1](https://github.com/idan/oauthlib/releases/tag/1.0.1) of oauthlib is released, so I believe you can merge fixes.

**Comment by masci** [comment]
@devoto13 yes and no, see https://github.com/idan/oauthlib/issues/367

**Comment by jeduden** [comment]
As mentioned in #281: the following line breaks with oauthlib 1.0.0.
https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L58

**Comment by masci** [comment]
Fixed in #245
