### ISSUE TITLE
Broken migration path from 0.8.1 to 0.9.0 

### ISSUE THREAD

**Issue by abarto** [evonove/django-oauth-toolkit#283]
It seems there's a problem with 0.9.0 new migrations:

    Traceback (most recent call last):
                    File "/home/vagrant/zoetis/apps/some_project/manage.py", line 11, in <module>
                      execute_from_command_line(sys.argv)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
                      utility.execute()
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
                      self.fetch_command(subcommand).run_from_argv(self.argv)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
                      self.execute(*args, **options.__dict__)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
                      output = self.handle(*args, **options)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
                      return self.handle_noargs(**options)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
                      call_command("migrate", **options)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
                      return klass.execute(*args, **defaults)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
                      output = self.handle(*args, **options)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
                      executor.migrate(targets, plan, fake=options.get("fake", False))
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
                      self.apply_migration(migration, fake=fake)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
                      migration.apply(project_state, schema_editor)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
                      operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
                      field,
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/mysql/schema.py", line 45, in add_field
                      super(MySQLGISSchemaEditor, self).add_field(model, field)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 42, in add_field
                      super(DatabaseSchemaEditor, self).add_field(model, field)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 380, in add_field
                      self.execute(sql, params)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 103, in execute
                      cursor.execute(sql, params)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
                      return super(CursorDebugWrapper, self).execute(sql, params)                                                                                                     [698/9157]
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
                      return self.cursor.execute(sql, params)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
                      six.reraise(dj_exc_type, dj_exc_value, traceback)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
                      return self.cursor.execute(sql, params)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
                      return self.cursor.execute(query, args)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
                      self.errorhandler(self, exc, value)
                    File "/home/vagrant/.virtualenvs/some_project/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
                      raise errorclass, errorvalue
                  django.db.utils.OperationalError: (1060, "Duplicate column name 'skip_authorization'")
              stdout:
                  Operations to perform:
                    Synchronize unmigrated apps: corsheaders, gis, rest_framework
                    Apply all migrations: oauth2_provider, default, user_preferences, admin, sessions, auth, sites, contenttypes
                  Synchronizing apps without migrations:
                    Creating tables...
                    Installing custom SQL...
                    Installing indexes...
                  Running migrations:
                    Applying oauth2_provider.0002_08_updates...

**Comment by pesachtw** [comment]
:+1:

**Comment by melizeche** [comment]
￼ bump

**Comment by synasius** [comment]
It looks like you already applied the migrations in 0002, maybe in a previous stage of your app using South, is it possible?

If it is the case, you can fake the 0002 migration
```
python manage.py migrate --fake oauth2_provider  0002
```

Otherwise you should add more details.
Thnx

**Comment by poswald** [comment]
There has been a small patch in the migrations since this was reported. Can you please retry and reopen this with more details if you still see issues.
