### ISSUE TITLE
Extending Application model on django1.7.1

### ISSUE THREAD

**Issue by pradnyam** [evonove/django-oauth-toolkit#305]
Hi,
I have followed the [document](https://django-oauth-toolkit.readthedocs.org/en/latest/advanced_topics.html) and the issue https://github.com/evonove/django-oauth-toolkit/issues/227.

But somehow I am not able to proceed further, 
Here is the traceback

```
October 15, 2015 - 12:26:36
Django version 1.7.1, using settings 'autoserve.settings'
Starting development server at http://localhost:8005/
Quit the server with CONTROL-C.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff7d6500e18>
Traceback (most recent call last):
  File "/<my-python-path>/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/<my-python-path>/site-packages/django/core/management/commands/runserver.py", line 105, in inner_run
    self.validate(display_num_errors=True)
  File "/<my-python-path>/site-packages/django/core/management/base.py", line 362, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/<my-python-path>/site-packages/django/core/management/base.py", line 414, in check
    raise CommandError(msg)
django.core.management.base.CommandError: System check identified some issues:

ERRORS:
oauth2_provider.AccessToken.application: (fields.E301) Field defines a relation with the model 'oauth2_provider.Application', which has been swapped out.
        HINT: Update the relation to point at 'settings.OAUTH2_PROVIDER_APPLICATION_MODEL'.
oauth2_provider.Grant.application: (fields.E301) Field defines a relation with the model 'oauth2_provider.Application', which has been swapped out.
        HINT: Update the relation to point at 'settings.OAUTH2_PROVIDER_APPLICATION_MODEL'.
oauth2_provider.RefreshToken.application: (fields.E301) Field defines a relation with the model 'oauth2_provider.Application', which has been swapped out.
        HINT: Update the relation to point at 'settings.OAUTH2_PROVIDER_APPLICATION_MODEL'.

System check identified 3 issues (0 silenced).
```

Please guide me

Kind Regards!!

**Comment by vinyll** [comment]
Hey @pradnyam. It's been a while now but I'm having the same issue. Do you remember how you solved that?

**Comment by vinyll** [comment]
Ok, the key point in my case was to extend `AbstractApplication`, and not `Application`.
Reference: http://django-oauth-toolkit.readthedocs.io/en/latest/advanced_topics.html#extending-the-application-model
