### ISSUE TITLE
Importlib library is missing

### ISSUE THREAD

**Issue by rwoloszyn** [evonove/django-oauth-toolkit#356]
I found error:

```
ERROR 2016-03-14 14:30:16,063 base 7553 139959887210240 Internal Server Error: /auth/convert-token/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/braces/views/_forms.py", line 22, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_social_oauth2/views.py", line 41, in post
    url, headers, body, status = self.create_token_response(request._request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2_provider/views/mixins.py", line 124, in create_token_response
    return core.create_token_response(request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2_provider/oauth2_backends.py", line 138, in create_token_response
    headers, extra_credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_social_oauth2/oauth2_endpoints.py", line 60, in create_token_response
    request, self.default_token_type)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 58, in create_token_response
    self.validate_token_request(request)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework_social_oauth2/oauth2_grants.py", line 84, in validate_token_request
    reverse(NAMESPACE + ":complete", args=(request.backend,)))
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/utils.py", line 29, in load_backend
    Backend = get_backend(BACKENDS, name)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/utils.py", line 51, in get_backend
    load_backends(backends, force_load=True)
  File "/usr/local/lib/python2.7/dist-packages/social/backends/utils.py", line 33, in load_backends
    backend = module_member(auth_backend)
  File "/usr/local/lib/python2.7/dist-packages/social/utils.py", line 56, in module_member
    module = import_module(mod)
  File "/usr/local/lib/python2.7/dist-packages/social/utils.py", line 50, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/social_auth/backends/__init__.py", line 30, in <module>`
```

Python 2.7.6, django framework

**Comment by synasius** [comment]
Hi @rwoloszyn 

can you add some detail to help us reproduce the issue? 

Also, I notice that you have an error in the "/auth/convert-token/" endpoint which is not an endpoint of Django OAuth Toolkit. Can you describe what your use case is?

thnx

**Comment by jleclanche** [comment]
This should not be an issue on the supported platforms.
